- name: Install required packages
  yum:
    name:
      - yum-utils
      - parted
      - xfsprogs 
      - git
      - python3
      - python3-pip
      - epel-release
    state: present

- name: Add Docker repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
- name: Install Docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes


- name: Create first partition on /dev/sdb (ext4)
  parted:
    device: /dev/sdb
    number: 1
    state: present
    part_type: primary
    fs_type: ext4
    part_start: 1MiB
    part_end: 512MiB

- name: Create second partition on /dev/sdb (xfs)
  parted:
    device: /dev/sdb
    number: 2
    state: present
    part_type: primary
    part_start: 512MiB
    part_end: 100%

- name: Make ext4 filesystem on /dev/sdb1
  filesystem:
    fstype: ext4
    dev: /dev/sdb1

- name: Make xfs filesystem on /dev/sdb2
  filesystem:
    fstype: xfs
    dev: /dev/sdb2

- name: Create mount directories
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - /data1
    - /data2

- name: Mount /dev/sdb1 to /data1
  mount:
    path: /data1
    src: /dev/sdb1
    fstype: ext4
    state: mounted

- name: Mount /dev/sdb2 to /data2
  mount:
    path: /data2
    src: /dev/sdb2
    fstype: xfs
    state: mounted

- name: Create test file in /data1
  copy:
    content: "this the file from local"
    dest: /data1/file1.txt

- name: Create test file in /data2
  copy:
    src: ./disk/files/one
    dest: /data2/file2.txt
- name: Add Docker repository
  shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo

- name: Install Docker
  yum:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: true
- name: run the container
  shell: |
    docker rm -f $(docker ps -a -q)
    docker run -d -p 8085:8085 {{ image_name }}
